substitutions:
  name: lum-iot40
  comment: Woonkamer switchplate

esp32:
  board: firebeetle32
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

external_components:
  - source: github://nielsnl68/esphome-gui
    components: [display, gui]
    refresh: 10s

psram:

spi:
  clk_pin: 18
  mosi_pin: 23
  miso_pin: 19

# Example minimal configuration entry
display:
  - platform: ili9xxx
    id: my_display
    #dimensions: 320x480
    model: ili9341
    cs_pin: 5
    dc_pin: 16
    rotation: 90
    auto_clear_enabled: false
    update_interval: never

  # Define a PWM output on the ESP32
output:
  - platform: ledc
    pin: 17
    id: gpio_17_backlight_pwm

# Define a monochromatic, dimmable light for the backlight
light:
  - platform: monochromatic
    output: gpio_17_backlight_pwm
    name: Display Backlight
    id: back_light
    restore_mode: ALWAYS_ON


time:
  - platform: homeassistant
    id: home_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - lambda: |
              id(mylabel).strftime("%H:%M", id(home_time).now());
    on_time_sync: 
      then:
        - lambda: |
            id(mylabel).strftime("%H:%M", id(home_time).now());

gui:
  id: mygui
  display_id: disp
  items:
    - type: label
      id: mylabel
      position: 40, 100
      dimensions: 100x25
    - type: label
      id: otherlabel
      position: 40, 200
      dimensions: 100x25
      text: "Hello!"
    - type: checkbox
      id: myswitch
      position: 0,0
      dimensions: 170x25
      switch_id: power_on
